module.exports = [{ id : 01 , name : "Thành phố Hà Nội"},
 { id : 02 , name : "tỉnh Hà Giang"},
 { id : 04 , name : "tỉnh Cao Bằng"},
 { id : 06 , name : "tỉnh Bắc Kạn"},
 { id : 08 , name : "tỉnh Tuyên Quang"},
 { id : 10 , name : "tỉnh Lào Cai"},
 { id : 11 , name : "tỉnh Điện Biên"},
 { id : 12 , name : "tỉnh Lai Châu"},
 { id : 14 , name : "tỉnh Sơn La"},
 { id : 15 , name : "tỉnh Yên Bái"},
 { id : 17 , name : "tỉnh Hoà Bình"},
 { id : 19 , name : "tỉnh Thái Nguyên"},
 { id : 20 , name : "tỉnh Lạng Sơn"},
 { id : 22 , name : "tỉnh Quảng Ninh"},
 { id : 24 , name : "tỉnh Bắc Giang"},
 { id : 25 , name : "tỉnh Phú Thọ"},
 { id : 26 , name : "tỉnh Vĩnh Phúc"},
 { id : 27 , name : "tỉnh Bắc Ninh"},
 { id : 30 , name : "tỉnh Hải Dương"},
 { id : 31 , name : "thành phố Hải Phòng"},
 { id : 33 , name : "tỉnh Hưng Yên"},
 { id : 34 , name : "tỉnh Thái Bình"},
 { id : 35 , name : "tỉnh Hà Nam"},
 { id : 36 , name : "tỉnh Nam Định"},
 { id : 37 , name : "tỉnh Ninh Bình"},
 { id : 38 , name : "tỉnh Thanh Hóa"},
 { id : 40 , name : "tỉnh Nghệ An"},
 { id : 42 , name : "tỉnh Hà Tĩnh"},
 { id : 44 , name : "tỉnh Quảng Bình"},
 { id : 45 , name : "tỉnh Quảng Trị"},
 { id : 46 , name : "tỉnh Thừa Thiên Huế"},
 { id : 48 , name : "thành phố Đà Nẵng"},
 { id : 49 , name : "tỉnh Quảng Nam"},
 { id : 51 , name : "tỉnh Quảng Ngãi"},
 { id : 52 , name : "tỉnh Bình Định"},
 { id : 54 , name : "tỉnh Phú Yên"},
 { id : 56 , name : "tỉnh Khánh Hòa"},
 { id : 58 , name : "tỉnh Ninh Thuận"},
 { id : 60 , name : "tỉnh Bình Thuận"},
 { id : 62 , name : "tỉnh Kon Tum"},
 { id : 64 , name : "tỉnh Gia Lai"},
 { id : 66 , name : "tỉnh Đắk Lắk"},
 { id : 67 , name : "tỉnh Đắk Nông"},
 { id : 68 , name : "tỉnh Lâm Đồng"},
 { id : 70 , name : "tỉnh Bình Phước"},
 { id : 72 , name : "tỉnh Tây Ninh"},
 { id : 74 , name : "tỉnh Bình Dương"},
 { id : 75 , name : "tỉnh Đồng Nai"},
 { id : 77 , name : "tỉnh Bà Rịa - Vũng Tàu"},
 { id : 79 , name : "thành phố Hồ Chí Minh"},
 { id : 80 , name : "tỉnh Long An"},
 { id : 82 , name : "tỉnh Tiền Giang"},
 { id : 83 , name : "tỉnh Bến Tre"},
 { id : 84 , name : "tỉnh Trà Vinh"},
 { id : 86 , name : "tỉnh Vĩnh Long"},
 { id : 87 , name : "tỉnh Đồng Tháp"},
 { id : 89 , name : "tỉnh An Giang"},
 { id : 91 , name : "tỉnh Kiên Giang"},
 { id : 92 , name : "thành phố Cần Thơ"},
 { id : 93 , name : "tỉnh Hậu Giang"},
 { id : 94 , name : "tỉnh Sóc Trăng"},
 { id : 95 , name : "tỉnh Bạc Liêu"},
 { id : 96 , name : "tỉnh Cà Mau"},]