module.exports = [
    "Japan",
    "Republic of Korea",
    "Viet Nam",
    "Singapore",
    "Australia",
    "Malaysia",
    "Cambodia",
    "Philippines",
    "Thailand",
    "Nepal",
    "Sri Lanka",
    "India",
    "America ",
    "Canada",
    "Germany",
    "France",
    "Italy",
    "Russian Federation",
    "The United Kingdom",
    "Belgium",
    "Finland",
    "Spain",
    "Sweden",
    "United Arab Emirates",
]